x-app-env: &app-env
  GO: 1

services:
  dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    working_dir: /app
    environment:
      <<: *app-env
    networks:
      - rater
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  cache:
    image: redis:alpine
    networks:
      - rater
    ports:
      - "6379:6379"

networks:
  rater:
