x-app-env: &app-env
  GOMAXPROCS: 1
  UPGRADER_APP_LOG_LEVEL: debug
  UPGRADER_REDIS_ADDRESS: cache:6379
  UPGRADER_REDIS_PASSWORD:
  UPGRADER_REDIS_DB: 0

services:
  upgrader:
    build:
      dockerfile: Dockerfile.dev
      context: .
    working_dir: /app
    environment:
      <<: *app-env
    networks:
      - upgrader
    depends_on:
      - cache
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - .app.cfg.yaml:/app/.app.cfg.yaml:ro

  cache:
    image: redis:alpine
    networks:
      - upgrader
    ports:
      - "6379:6379"

networks:
  upgrader:
